# Generated by Django 2.1.1 on 2018-10-17 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=255)),
                ('remark', models.TextField()),
                ('deleted', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verify', models.BooleanField()),
                ('site_closed', models.BooleanField()),
            ],
        ),
    ]
