# Generated by Django 2.1.1 on 2018-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0002_site_alert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_alert',
            new_name='Website_alert',
        ),
    ]
