# Generated by Django 2.1.1 on 2018-12-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0003_auto_20181102_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website_alert',
            options={'permissions': (('can_verify', 'Can verify a website alert'),)},
        ),
    ]
