# Generated by Django 2.1.1 on 2019-02-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0005_auto_20190212_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website_alert',
            old_name='anitisem_france',
            new_name='antisem_france',
        ),
    ]
