# Generated by Django 2.1.1 on 2019-02-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0006_auto_20190212_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_alert',
            name='extern_pseudo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='website_alert',
            name='main_quotes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='website_alert',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
