# Generated by Django 2.1.1 on 2019-04-30 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitereview', '0009_auto_20190414_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('website_alert', 'user')},
        ),
    ]
