# Generated by Django 2.2.2 on 2019-06-16 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0010_auto_20190430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_alert',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='website_alert',
            name='voted_by',
            field=models.ManyToManyField(related_name='website_alerts', through='sitereview.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
