# Generated by Django 2.2.2 on 2019-10-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0011_auto_20190616_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website_alert',
            options={'permissions': (('can_verify', 'Can verify a website alert'), ('can_unverify', 'Can unverify a website alert'))},
        ),
    ]
