# Generated by Django 2.2.2 on 2019-10-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereview', '0013_auto_20191022_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website_alert',
            options={'permissions': (('can_verify', 'Can verify a website alert'), ('can_unverify', 'Can unverify a website alert'), ('can_edit', 'Can edit a website alert'))},
        ),
    ]
